CREATE OR REPLACE VIEW SALARY_VU AS
SELECT e.LAST_NAME "Employee", d.DEPARTMENT_NAME "Department",
       e.SALARY "Salary", j.GRADE_LEVEL "Grades"
FROM EMPLOYEES e, DEPARTMENTS d, JOB_GRADES j
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
AND e.SALARY BETWEEN j.LOWEST_SAL AND j.HIGHEST_SAL;
       