COLUMN dummy NOPRINT
SELECT JOB_ID, DEPARTMENT_ID, 1 dummy
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10
UNION
SELECT JOB_ID, DEPARTMENT_ID, 2
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
UNION
SELECT JOB_ID, DEPARTMENT_ID, 3
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20
ORDER BY 3;