SELECT LAST_NAME, DEPARTMENT_NAME, LOCATION_ID, CITY
FROM EMPLOYEES e
JOIN DEPARTMENTS d
ON (d.DEPARTMENT_ID = e.DEPARTMENT_ID)
JOIN LOCATIONS l
ON (d.LOCATION_ID = l.LOCATION_ID)
AND e.COMMISSION_PCT IS NOT NULL;