DESCRIBE JOB_GRADES;
SELECT e.LAST_NAME, e.JOB_ID, d.DEPARTMENT_NAME,
       e.SALARY, j.GRADE_LEVEL
FROM EMPLOYEES E JOIN DEPARTMENTS d
ON (e.DEPARTMENT_ID = d.DEPARTMENT_ID)
JOIN JOB_GRADES j
ON (e.SALARY BETWEEN j.LOWEST_SAL AND j.HIGHEST_SAL);