DESCRIBE JOB_GRADES;
SELECT e.LAST_NAME, e.JOB_ID, d.DEPARTMENT_NAME,
       e.SALARY, j.GRADE_LEVEL
FROM EMPLOYEES e, DEPARTMENTS d, JOB_GRADES j
WHERE e.DEPARTMENT_ID = d.DEPARTMENT_ID
AND e.SALARY BETWEEN j.LOWEST_SAL AND j.HIGHEST_SAL;