SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES)
AND DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                      FROM EMPLOYEES
                      WHERE LAST_NAME LIKE '%u%');